const ACT = {
  MARKREQUEST: {
    PENDING: 'APP/MARKREQUEST_PENDING',
    SUCCESS: 'APP/MARKREQUEST_SUCCESS',
    FAILED: 'APP/MARKREQUEST_FAILED',
    CANCELLED: 'APP/MARKREQUEST_CANCELLED',
  },
  INVOKECALLBACK: 'APP/INVOKECALLBACK',
  LOG: 'APP/LOG',
  NOOP: 'APP/NOOP',
  APP: {
    INIT: 'APP/INIT',
    INITED: 'APP/INITED',
  },
  INTL: {
    LOCALE: {
      CHG: 'APP/LOCALE_CHG',
      CHGED: 'APP/LOCALE_CHGED',
    },
  },
  AUTH: {
    LOGINFORM: {
      CHGED: 'APP/LOGINFORM_CHGED',
      CLEANMSG: 'APP/LOGINFORM_CLEANMSG',
    },
    LOGIN: 'APP/AUTH_LOGIN',
    LOGOUT: 'APP/AUTH_LOGOUT',
    LOGINFAILED: 'APP/AUTH_LOGINFAILED',
    SETAUTHSTATE: 'APP/AUTH_SETAUTHSTATE',
    SAVELOGINUSER: 'APP/AUTH_SAVELOGINUSER',
    REMOVELOGINUSER: 'APP/AUTH_REMOVELOGINUSER',
    RERESHTOKEN: 'APP/AUTH_RERESHTOKEN',
  },
};

export default ACT;
